### ISSUE TITLE
Add calculated variables to the QDS/REDCap data

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/link2care_public#39]
# Overview

We completed the code to merge the QDS survey data with the REDCap survey data. Now that we have all of the data in a single long data frame, we need to create the calculated variables. 

There is some existing SPSS code to do this somewhere, and we already adapted it for R here: https://github.com/brad-cannell/link2care_public/blob/master/one_offs/data_survey_01_import.Rmd

However, that code was only used on wide (not long) data for a visits 1 and 2. So, it will need to be adapted to be applied to the combined analysis data. It should still be a good start, though.

**Comment by mbcann01** [comment]
@skurada1 , I think this is our next step. Please let me know if you have any questions.

**Comment by skurada1** [comment]
@mbcann01, sounds good! I'll get started and let you know if I have questions.
