### ISSUE TITLE
Move the code from one_offs/data_survey_01_import_Rmd into the combined data pipeline

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/link2care_public#52]
# Overview 

In #50 , I discovered that in `data_survey_23_codebook.Rmd` the `label()` code (lines 106-123) is no longer working. The column names `cell_have_f` through `facebook_active_f` no longer exist in the `combined_participant_data.rds` for some reason. I'm not sure why.

Those variables are created in `one_offs/data_survey_01_import_Rmd`. I need to move that code into the combined participant data pipeline.

Doing so may solve other data problems as well.

# Left off at

2023-08-30:
- Line 1092 of `data_survey_qds_import_v1.qmd`.
- I need to import v3-v5 using the same process as above.
- But first:
  - Work out the process of combining the v1 and v2.
  - Work out the process of creating calculated variables in the joined data frame. Borrow code from `data_survey_01_import.Rmd`.

**Comment by corvidfox** [comment]
I have re-designed the variable import an reorganization process for the data sets. V1-V5 have been successfully stacked while maintaining the SPSS attribute values. Next I will be creating the calculated variables in the joined data frame.

**Comment by corvidfox** [comment]
Calculated QDS variables have been recreated in R. These variables have also been added to the variable map to ensure proper positioning, and facilitate point-fixes.

Next step would be to check group assignment between the QDS and both REDCap and the Master Log.

Then, processing/stacking the REDCap variables to merge into the QDS data set, and so on.

**Comment by corvidfox** [comment]
Group assignments have been verified against the Master Log and REDCap data. Standardized/confirmed group assignments added to combined QDS data set. QDS variables that dropped their attributes after merging/processing were caught and picked their attributes back up.

**Comment by corvidfox** [comment]
Processing has been revised/refined based on feedback on variable-map process. Helper functions and guide/tutorial of variable map process created. Variable-map creation isolated as "first step" to be completed for all source data sets. Identified SPSS calculated variables to be dropped. Data sets to be individually processed with variable map and refined, merged, and then calculated variables recreated on the aggregate set.
